//
//  SearchPresenter.swift
//  GithubSearchCleanSwift
//
//  Created by 한지민 on 2022/03/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentFetchedRepositories(response: Search.FetchRepositories.Response)
}

class SearchPresenter {
    weak var viewController: SearchDisplayLogic?
}

extension SearchPresenter: SearchPresentationLogic {
    func presentFetchedRepositories(response: Search.FetchRepositories.Response) {
        let viewModel = Search.FetchRepositories.ViewModel(fetchedRepositories: response.items)
        self.viewController?.displayRepositories(viewModel: viewModel)
    }
}
